import { env } from "./env.js";

export const envKeys = {
  PORT: +(env.PORT ?? 8000),
  ACCESS_SECRET: env.ACCESS_SECRET,
  REFRESH_SECRET: env.REFRESH_SECRET,
  DATABASE_URL: env.DATABASE_URL,
  CLIENT_URL: env.CLIENT_URL,
  NODE_ENV: env.NODE_ENV,
  CONVEX_URL: env.CONVEX_URL,
  CONVEX_ADMIN_KEY: env.CONVEX_ADMIN_KEY,
  COOKIE_SECURE: env.COOKIE_SECURE,
  COOKIE_DOMAIN: env.COOKIE_DOMAIN,
  DISABLE_LOGGING: env.DISABLE_LOGGING === "true",
};
